### ISSUE TITLE
Add loader while making api calls

### ISSUE THREAD

**Issue by karankoder** [GauravGupta993/MERN-Templates#15]
Currently, when making API calls within the application, there is no visual feedback to indicate that a request is being processed. This can lead to confusion for users, as they may not be aware that their request is being handled, especially if there is a delay in the response.

To improve user experience and provide clear feedback, we need to implement a loader that appears while the API call is in progress. This loader should inform users that their request is being processed, enhancing the responsiveness and interactivity of the application.

**Comment by karankoder** [comment]
@GauravGupta993 please add hacktoberfest tag in this issue and assign it to me.

**Comment by GauravGupta993** [comment]
@karankoder Create the loader as a template and place it in the template design folder so that the same loader might be reused again in the future.
